/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as MomentumRouteImport } from './routes/momentum'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as IndexRouteImport } from './routes/index'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentumRoute = MomentumRouteImport.update({
  id: '/momentum',
  path: '/momentum',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/insights': typeof InsightsRoute
  '/milestones': typeof MilestonesRoute
  '/momentum': typeof MomentumRoute
  '/players': typeof PlayersRoute
  '/predictions': typeof PredictionsRoute
  '/teams': typeof TeamsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/insights': typeof InsightsRoute
  '/milestones': typeof MilestonesRoute
  '/momentum': typeof MomentumRoute
  '/players': typeof PlayersRoute
  '/predictions': typeof PredictionsRoute
  '/teams': typeof TeamsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fantasy': typeof FantasyRoute
  '/insights': typeof InsightsRoute
  '/milestones': typeof MilestonesRoute
  '/momentum': typeof MomentumRoute
  '/players': typeof PlayersRoute
  '/predictions': typeof PredictionsRoute
  '/teams': typeof TeamsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fantasy'
    | '/insights'
    | '/milestones'
    | '/momentum'
    | '/players'
    | '/predictions'
    | '/teams'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fantasy'
    | '/insights'
    | '/milestones'
    | '/momentum'
    | '/players'
    | '/predictions'
    | '/teams'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/fantasy'
    | '/insights'
    | '/milestones'
    | '/momentum'
    | '/players'
    | '/predictions'
    | '/teams'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FantasyRoute: typeof FantasyRoute
  InsightsRoute: typeof InsightsRoute
  MilestonesRoute: typeof MilestonesRoute
  MomentumRoute: typeof MomentumRoute
  PlayersRoute: typeof PlayersRoute
  PredictionsRoute: typeof PredictionsRoute
  TeamsRoute: typeof TeamsRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/momentum': {
      id: '/momentum'
      path: '/momentum'
      fullPath: '/momentum'
      preLoaderRoute: typeof MomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FantasyRoute: FantasyRoute,
  InsightsRoute: InsightsRoute,
  MilestonesRoute: MilestonesRoute,
  MomentumRoute: MomentumRoute,
  PlayersRoute: PlayersRoute,
  PredictionsRoute: PredictionsRoute,
  TeamsRoute: TeamsRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
